# docker-compose.prod.yml
version: '3.8'
services:
  api:
    build: 
      context: ./backend
      target: production
    ports:
      - "9091:9091"
    command: npm start
    environment:
      - NODE_ENV=production
      - METRICS_PORT=9091

  data-ingestion:
    build:
      context: ./backend/data-ingestion
      target: production
    command: npm start
    environment:
      - NODE_ENV=production

  data-processor:
    build: 
      context: ./backend/data-processor
      target: production
    ports:
      - "9093:9093"
    command: npm start
    environment:
      - NODE_ENV=production
      - METRICS_PORT=9093
    depends_on:
      db:
        condition: service_healthy

  kafka:
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"